apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev
  labels:
    env: dev
spec:
  limits:
    - default:
        cpu: "100m"
        memory: "100Mi"
      defaultRequest:
        cpu: "90m"
        memory: "100Mi"
      max:
        cpu: "150M"
        memory: "150Mi"
      min:
        cpu: "90m"
        memory: "100Mi"
      type: Container
