apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-auto-scale-deployment
  labels:
    app: web_v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web_v1
  template:
    metadata:
      labels:
        app: web_v1
    spec:
      containers:
        - name: webapp
          image: lovelearnlinux/webserver:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "60m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "80Mi"
              
