apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8-autoscaler
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8-auto-scale-deployment
  targetCPUUtilizationPercentage: 30
