apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: web
spec:
  containers:
    - name: webapp
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name:  webroot
          mountPath:  /usr/share/nginx/html
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: myclaim
