apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: webcont
      image: coolgourav147/nginx-custom
      volumeMounts:
        - name: test
          mountPath: "/config"
  volumes:
    - name: test
      configMap:
        name: cm4
