apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: webcont
      image: coolgourav147/nginx-custom
      env:
        - name: db_ip
          valueFrom:
            configMapKeyRef:
              key: database_ip
              name: envcm2
        - name: db_user
          valueFrom:
            configMapKeyRef:
              key: database_user
              name: envcm2
        - name: db_passwd
          valueFrom:
            configMapKeyRef:
              key: database_pass
              name: envcm2
