apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image:  nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: webroot
          mountPath: /usr/share/nginx/html
  volumes:
    - name: webroot
      emptyDir: {}
