apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-1
  labels:
    app: web
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /contdata
    server: 192.168.1.24
