apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: webapp
spec:
  nodeName: master
  containers:
    - name: webapp
      image:  nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: webroot
          mountPath: /usr/share/nginx/html
  volumes:
    - name: webroot
      hostPath:
        path: /nginx

## This volume is created at the node first and then its mounted to the pod.
## I have used nodeselector in the configuration which will schedule the pod on master node because mount path is created there only.        
  
