apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: webcont
      image: coolgourav147/nginx-custom
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              key: username
              name: sec1
        - name: password
          valueFrom:
            secretKeyRef:
              key: password
              name: sec1
