apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    app: web
spec:
  containers:
    - name: webcont
      image: coolgourav147/nginx-custom
      volumeMounts:
        - name: testvol
          mountPath: /secrets
  volumes:
    - name: testvol
      secret:
        secretName: envsec1
